Repository eveningkid/denodb, pull requests merged in 2020-09, with the labels that each got.

#109 LEFT JOIN and LEFT OUTER JOIN support
  lib/model.ts
  lib/query-builder.ts
  lib/translators/sql-translator.ts
Labels: enhancement

#113 fix(deps.ts): Deno 1.3.3 Sample. Error - TS2790 [ERROR]: The operand …
  deps.ts
Labels: bug

#125 perf: replace redundant spread on each iteration
  lib/connectors/mongodb-connector.ts
  lib/database.ts
  lib/model.ts
  lib/translators/sql-translator.ts
Labels: performance
