Repository eveningkid/denodb, pull requests merged in 2020-05, with the labels that each got.

#6 Add unique field option and fix #4
  lib/helpers/fields.ts
  lib/query-builder.ts
Labels: enhancement

#8 Fix #7 create table if not exists by default
  lib/model-initializer.ts
  lib/query-builder.ts
  lib/translators/sql-translator.ts
Labels: enhancement

#12 Save SQLite database file on query
  lib/connectors/sqlite3-connector.ts
Labels: enhancement

#15 Make Database.sync synchronous
  lib/database.ts
Labels: bug

#17 Update README to add another example for field
  README.md
Labels: documentation

#19 Fix SQLite3 connector not running multiple subqueries in a single query
  lib/connectors/sqlite3-connector.ts
  lib/helpers/fields.ts
Labels: bug, enhancement

#23 Add data types
  README.md
  lib/data-types.ts
  lib/helpers/fields.ts
  lib/query-builder.ts
Labels: documentation, enhancement

#26 Upgrade deno sqlite 2
  deps.ts
  lib/connectors/sqlite3-connector.ts
Labels: bug, enhancement
